/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package amc.group.pkg9;

import java.awt.Color;

public class CustomerNotif extends javax.swing.JPanel {

    private final Customer customer; 

    private static final int COL_USER   = 0;
    private static final int COL_TITLE  = 1;
    private static final int COL_MSG    = 2;
    private static final int COL_DATE   = 3;
    private static final int COL_STATUS = 4;
    
    // keep loaded rows so hidden notifID can be accessed
    
    private java.util.List<NotifHandler.Row> currentRows = java.util.Collections.emptyList();

    
    
    public CustomerNotif(Customer customer) {
        initComponents();
        
        this.customer = customer;
        initComponents();

        configureTable();
        wireSelection();
        loadNotifs();

        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setHorizontalScrollBarPolicy(
            javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        
        setOpaque(true); 
        setBackground(Color.decode("#ece8e1"));
        
    }
    
    
    
    
    
    private void configureTable() {

        String[] cols = {"User ID", "Title", "Message", "Sent Date", "Status"};
    
        javax.swing.table.DefaultTableModel m = new javax.swing.table.DefaultTableModel(cols, 0) {
        
            @Override 
            public boolean isCellEditable(int r, int c) { 
                return false; 
            }
        };
    
        jTable1.setModel(m);
        jTable1.getTableHeader().setReorderingAllowed(false);

        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        
        jScrollPane1.setHorizontalScrollBarPolicy(
                javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED
        );

        int[] w = {100, 160, 480, 160, 80};

        int colsInModel = jTable1.getColumnModel().getColumnCount();
        for (int i = 0; i < Math.min(w.length, colsInModel); i++) {
            jTable1.getColumnModel().getColumn(i).setPreferredWidth(w[i]);
        }

    }
    

    
    
    
    private void loadNotifs() {
        
        currentRows = NotifHandler.loadForCustomer(customer.getId());

        javax.swing.table.DefaultTableModel m = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        m.setRowCount(0);
        for (var r : currentRows) {
            m.addRow(new Object[]{
                r.staffId,
                r.title,
                r.message,
                r.sentAt,
                r.read ? "Read" : "Unread"
            });
        }
    }
    
    
    
    private void wireSelection() {
        jButton1.setEnabled(false);

        jTable1.getSelectionModel().addListSelectionListener(e -> {
            jButton1.setEnabled(jTable1.getSelectedRow() >= 0);
        });
    }

    
    
    
    private void markAsRead() {
    
        int viewRow = jTable1.getSelectedRow();
        if (viewRow < 0) return;
    
        int modelRow = jTable1.convertRowIndexToModel(viewRow);

        NotifHandler.Row r = currentRows.get(modelRow);
        NotifHandler.markAsRead(r.notifId, r.staffId);

        jTable1.setValueAt("Read", modelRow, COL_STATUS);
        javax.swing.JOptionPane.showMessageDialog(this, "Marked as read.");
    }


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Notification");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Mark As Read");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        markAsRead();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
