/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package amc.group.pkg9;


public class CustCurrentAppointment extends javax.swing.JPanel {

    private final Customer customer;                     

    private static final int  COL_DATE=3, COL_TIME=4, COL_STATUS=5;

    public CustCurrentAppointment(Customer customer) {
        
        initComponents(); 
        
        java.awt.Color bg = java.awt.Color.decode("#ece8e1");
        this.customer = customer;
        
        setOpaque(true);
        setBackground(bg);
        
        if (jPanel1 != null) { jPanel1.setOpaque(true); jPanel1.setBackground(bg); }
        
        configureTable();
        loadRows();
        
    }

    private void configureTable() {
    
        String[] cols = {"Appointment ID","Name","Doctor Name","Date","Start Time","Status"};
    
        javax.swing.table.DefaultTableModel m = new javax.swing.table.DefaultTableModel(cols, 0) {
        
            @Override 
            public boolean isCellEditable(int r,int c){ 
                return false; }
            };
    
        jTable1.setModel(m);
    
        jTable1.getTableHeader().setReorderingAllowed(false);
    
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setHorizontalScrollBarPolicy(
            javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED
        );

        int[] w = {120,160,180,120,110,110};
        for (int i = 0; i < w.length; i++)
            jTable1.getColumnModel().getColumn(i).setPreferredWidth(w[i]);

        var center = new javax.swing.table.DefaultTableCellRenderer();
        center.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTable1.getColumnModel().getColumn(COL_DATE).setCellRenderer(center);
        jTable1.getColumnModel().getColumn(COL_TIME).setCellRenderer(center);
        jTable1.getColumnModel().getColumn(COL_STATUS).setCellRenderer(center);
    }


    private void loadRows() {
        var m = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        m.setRowCount(0);
        java.util.List<Appointment> rows =
            AppointmentFileHandler.loadCurrentPendingByCustomer(customer.getId()); // you already have this loader
        for (Appointment a : rows) {
            m.addRow(new Object[]{
                a.getAppointmentId(),
                customer.getName(),        // derived from logged-in customer
                a.getDoctorName(),         
                a.getDate(),
                a.getTime(),
                a.getStatus().name()       // pending
            });
        }   
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Current Appointment");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
